### PR TITLE
Update to latest robot model

### PR DESCRIPTION
**Pull request by clalancette**
Update to the latest robot_model.  This is a merge of what is currently on the ros2 with the head of the upstream kinetic-devel.  This one is actually mergeable :).

connects to ros2/ros2#419

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Would it make sense to finish the migration of the packages to other repos before syncing ? https://github.com/ros/robot_model/issues/195

**Comment by clalancette** [comment]
> Would it make sense to finish the migration of the packages to other repos before syncing ? ros#195

Since we don't have an exact timeline for that (just "before Melodic"), and I'd like to get the licensing problem straightened out, I think we can go ahead with this.  It will be easy enough to split urdf changes out later, similar to what I did for kdl_parser.

**Comment by mikaelarguedas** [comment]
@clalancette FYI: all robot_model ROS 1 PRs have been merged so this isn't blocked anymore

**Comment by clalancette** [comment]
Closing this, as we no longer need robot_model in the base of ros2.

**Comment by mikaelarguedas** [comment]
Deleting this branch as I don't know when we will delete this repository completely

**Pull request closed without merging**
